ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CONTENT_WRITER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DESIGNER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'REVIEWER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PUBLISHER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'VIEWER';
